# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.lblSalida = QtWidgets.QLabel(Widget)
        self.lblSalida.setGeometry(QtCore.QRect(130, 350, 581, 101))
        self.lblSalida.setStyleSheet("color: rgb(0, 0, 255);\n"
"font: 26pt \"MS Shell Dlg 2\";")
        self.lblSalida.setObjectName("lblSalida")
        self.TXTpWD = QtWidgets.QLineEdit(Widget)
        self.TXTpWD.setGeometry(QtCore.QRect(230, 130, 331, 71))
        self.TXTpWD.setObjectName("TXTpWD")
        self.btnPwd = QtWidgets.QPushButton(Widget)
        self.btnPwd.setGeometry(QtCore.QRect(290, 250, 201, 51))
        self.btnPwd.setObjectName("btnPwd")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.lblSalida.setText(_translate("Widget", "PYTHON"))
        self.btnPwd.setText(_translate("Widget", "Validar"))
